api:
  version: "@project.version@"
  base-url: ${API_BASE_URL}
  endpoints:
    verify-user-path: /api/v1/auth/verify

spring:
  application:
    name: "@project.artifactId@"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: roomify
  graphql:
    graphiql:
      enabled: true
  flyway:
    enabled: true
    default-schema: roomify
    schemas: roomify
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    display-request-duration: true
    doc-expansion: none
    operationsSorter: method
    tagsSorter: alpha

brevo:
  api-key: ${BREVO_API_KEY}
  sender-email: roomify.dev@proton.me
  sender-name: Roomify
  base-url: https://api.brevo.com/v3
  brevo-smtp-path: /smtp/email

resilience4j:
  retry:
    instances:
      sendEmailRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - com.roomify.shared.exception.TechniqueApiException
          - java.io.IOException
          - org.springframework.web.reactive.function.client.WebClientRequestException
        ignore-exceptions:
          - com.roomify.shared.exception.ClientApiException
  ratelimiter:
    instances:
      creationalRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 60s
        timeoutDuration: 0
      loginUserRateLimiter:
        limitForPeriod: 20
        limitRefreshPeriod: 60s
        timeoutDuration: 0

security:
  jwt:
    secret: ${JWT_SECRET}

server:
  port: 8080
  forward-headers-strategy: framework