SET search_path TO roomify;

-- Récupération du user super_admin
WITH admin_user AS (SELECT id
                    FROM roomify.users
                    WHERE email = 'super.admin@gmail.com')

INSERT
INTO roomify.places (id,
                     name,
                     description,
                     type,
                     address,
                     normalized_address,
                     capacity,
                     price_per_hour,
                     status,
                     user_id)
SELECT nextval('roomify.place_seq'),
       p.name,
       p.description,
       p.type,
       p.address,
       -- Normalisation SQL
       LOWER(REGEXP_REPLACE(TRIM(p.address), '\s+', ' ', 'g')),
       p.capacity,
       p.price,
       p.status,
       admin_user.id
FROM admin_user,
     (VALUES ('Modern Meeting Room',
              'Spacious meeting room with projector and whiteboard',
              'MEETING_ROOM',
              '10 rue de Paris, 75001 Paris',
              10,
              25.00,
              'APPROVED'),
             ('Cozy Coworking Space',
              'Quiet coworking space ideal for freelancers',
              'COWORKING_SPACE',
              '5 avenue de Lyon, 69000 Lyon',
              20,
              15.00,
              'APPROVED'),
             ('Large Event Hall',
              'Perfect for corporate events and meetups',
              'EVENT_SPACE',
              '20 boulevard Haussmann, 75009 Paris',
              100,
              120.00,
              'PENDING'),
             ('Private Party Room',
              'Ideal for birthdays and private parties',
              'PARTY_ROOM',
              '3 rue des Fêtes, 75019 Paris',
              30,
              80.00,
              'REJECTED'),
             ('Photo Studio Pro',
              'Professional studio with lighting equipment',
              'STUDIO',
              '12 rue de la Photo, 75002 Paris',
              8,
              50.00,
              'APPROVED'),
             ('Startup Meeting Hub',
              'Modern space for startup meetings',
              'MEETING_ROOM',
              'Station F, 5 Parvis Alan Turing, 75013 Paris',
              6,
              35.00,
              'PENDING'),
             ('Open Workspace Loft',
              'Loft style coworking with open space',
              'COWORKING_SPACE',
              '8 rue Oberkampf, 75011 Paris',
              25,
              18.00,
              'APPROVED')) AS p(name, description, type, address, capacity, price, status);